movies = [
    {
        "title": "Swargandharva Sudhir Phadke",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 01, 2024",
        "url": "https://www.rottentomatoes.com/m/swargandharva_sudhir_phadke",
    },
    {
        "title": "Malayalee from India",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 01, 2024",
        "url": None,
    },
    {
        "title": "The Idea of You",
        "critics_score": "82",
        "audience_score": "",
        "released_date": "Opened May 02, 2024",
        "url": None,
    },
    {
        "title": "Jeanne du Barry",
        "critics_score": "46",
        "audience_score": "94",
        "released_date": "Opened May 02, 2024",
        "url": None,
    },
    {
        "title": "Macbeth: Ralph Fiennes & Indira Varma",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 02, 2024",
        "url": None,
    },
    {
        "title": "The Fall Guy",
        "critics_score": "83",
        "audience_score": "87",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Unfrosted",
        "critics_score": "42",
        "audience_score": "50",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Tarot",
        "critics_score": "12",
        "audience_score": "58",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "I Saw the TV Glow",
        "critics_score": "88",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "New Life",
        "critics_score": "95",
        "audience_score": "85",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Star Wars: Episode I - The Phantom Menace",
        "critics_score": "52",
        "audience_score": "59",
        "released_date": "Re-released May 03, 2024",
        "url": None,
    },
    {
        "title": "Evil Does Not Exist",
        "critics_score": "92",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Something in the Water",
        "critics_score": "",
        "audience_score": "40",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Chief of Station",
        "critics_score": "",
        "audience_score": "0",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Mars Express",
        "critics_score": "100",
        "audience_score": "80",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Dragonkeeper",
        "critics_score": "",
        "audience_score": "67",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Wildcat",
        "critics_score": "48",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "The Roundup: Punishment",
        "critics_score": "90",
        "audience_score": "71",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Catching Fire: The Story of Anita Pallenberg",
        "critics_score": "83",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Slow",
        "critics_score": "90",
        "audience_score": "100",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Thabo and the Rhino Case",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Lost Soulz",
        "critics_score": "93",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Finding The Money",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": "https://www.rottentomatoes.com/m/finding_the_money",
    },
    {
        "title": "This World Is Not My Own",
        "critics_score": "100",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": "https://www.rottentomatoes.com/m/this_world_is_not_my_own",
    },
    {
        "title": "Who Is Stan Smith?",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": "https://www.rottentomatoes.com/m/who_is_stan_smith",
    },
    {
        "title": "Walled Off",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
    {
        "title": "Adiós Buenos Aires",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": "https://www.rottentomatoes.com/m/adios_buenos_aires",
    },
    {
        "title": "Kitty the Killer",
        "critics_score": "",
        "audience_score": "",
        "released_date": "Opened May 03, 2024",
        "url": None,
    },
]
